DjangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('market.urls', namespace="market"))
]

market/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import get_books, get_book, get_authors, get_author, get_categories, get_category

app_name = 'market'

urlpatterns = [
    path('books/', get_books, name='get_books'),
    path('books/<int:book_id>/', get_book, name='get_book'),
    path('category/', get_categories, name='get_categories'),
    path('category/<int:category_id>/', get_category, name='get_category'),
    path('author/', get_authors, name='get_authors'),
    path('author/<int:author_id>/', get_author, name='get_author'),
]

market/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

class Book(models.Model):
    HARD_COVER = 'HC'
    SOFT_COVER = 'SC'
    SPECIAL_COVER = 'SPC'
    COVER_CHOICES = [
        (HARD_COVER, _('Hard cover')),
        (SOFT_COVER, _('Soft cover')),
        (SPECIAL_COVER, _('Special cover'))
    ]
    cover = models.CharField(max_length=3, choices=COVER_CHOICES, default=SOFT_COVER, verbose_name=_('cover type'))
    name = models.CharField(max_length=255, verbose_name=_("Name"))
    page_count = models.PositiveIntegerField(verbose_name=_("Page Count"))
    author = models.ForeignKey('Author', on_delete=models.CASCADE, related_name='books', verbose_name=_('author'), null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name=_("Price"))
    image = models.ImageField(upload_to='media/', verbose_name=_("Image"))
    categories = models.ManyToManyField('Category', related_name='books', verbose_name=_('categories'))
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Book")
        verbose_name_plural = _("Books")


class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name=_("Category Name"))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")


class Author(models.Model):
    first_name = models.CharField(max_length=255, verbose_name=_('First name'))
    last_name = models.CharField(max_length=255, verbose_name=_('Last Name'))
    birth_date = models.DateField()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    class Meta:
        verbose_name = _('Author')
        verbose_name_plural = _('Authors')

market/views.py

from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, Page

from .models import Book, Author, Category


def get_books(request):
    books = Book.objects.all()
    paginator = Paginator(books, per_page = 2)
    page_num = int(request.GET.get('page', 1))
    page : Page = paginator.get_page(page_num)
    return render(request, 'index.html', {'books': page})



def get_book(request, book_id):
    book = get_object_or_404(Book, id=book_id)
    return render(request, 'detail.html', {'books': [book]})

def get_authors(request):
    authors = Author.objects.all()
    paginator = Paginator(authors, per_page=2)
    page_num = int(request.GET.get('page', 1))
    page: Page = paginator.get_page(page_num)
    return render(request, 'author_index.html', {'authors': page})


def get_author(request, author_id):
    author = get_object_or_404(Author, pk=author_id)
    return render(request, 'author_detail.html', {'author': author})

def get_categories(request):
    categories = Category.objects.all()
    paginator = Paginator(categories, per_page=2)
    page_num = request.GET.get('page')
    page: Page = paginator.get_page(page_num)
    return render(request, 'category_index.html', {'categories': page})


def get_category(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    books = category.books.all()
    return render(request, 'category_index.html', {'category': category, 'books': books})

market/templates/author_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Book</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f5f5f5;
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }
        .book {
            background-color: #fff;
            border-radius: 5px;
            padding: 20px;
            margin-bottom: 20px;
        }
        .book h2 {
            color: #333;
            font-size: 24px;
            margin-bottom: 10px;
        }
        .book p {
            color: #666;
            margin: 5px 0;
        }
        .book p strong {
            color: #333;
        }
    </style>
</head>
<body>
    <h2>{{ author.first_name }} {{ author.last_name }} </h2>
    <h2>Data of Birth {{ author.birth_date }}</h2>
</body>
</html>

market/templates/author_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>List of Authors</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f5f5f5;
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }
        h1 {
            color: #333;
            text-align: center;
            margin-bottom: 20px;
        }
        ul {
            list-style: none;
            padding: 0;
            margin: 0;
        }
        li {
            margin-bottom: 10px;
        }
        a {
            text-decoration: none;
            color: #007bff;
        }
        a:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>
<div class="container">
    <h1>List of Authors</h1>
    <ul>
        {% for author in authors %}
            <li><a href="{% url 'market:get_author' author.pk %}">{{ author }}</a></li>
        {% endfor %}
    </ul>
    </div>
</div>
</body>
</html>

market/templates/category_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Book Categories</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f5f5f5;
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }
        h1 {
            color: #333;
            text-align: center;
            margin-bottom: 20px;
        }
        ul {
            list-style: none;
            padding: 0;
            margin: 0;
        }
        li {
            margin-bottom: 10px;
        }
        a {
            text-decoration: none;
            color: #007bff;
        }
        a:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>
<div class="container">
    <h1>Book Categories</h1>
    <div>
        <ul>
            {% for category in categories %}
            <li>
                <a href="{% url 'market:get_category' category.id %}">{{ category }}</a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
</body>
</html>

market/templates/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Book</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f5f5f5;
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }
        .book {
            background-color: #fff;
            border-radius: 5px;
            padding: 20px;
            margin-bottom: 20px;
        }
        .book h2 {
            color: #333;
            font-size: 24px;
            margin-bottom: 10px;
        }
        .book p {
            color: #666;
            margin: 5px 0;
        }
        .book p strong {
            color: #333;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Book</h1>
        <div class="book-list">
            {% for book in books %}
            <div class="book">
                <h2>{{ book.name }}</h2>
                <p><strong>Page count:</strong> {{ book.page_count }}</p>
                <p><strong>Category:</strong> {{ book.category }}</p>
                <p><strong>Author name:</strong> {{ book.author_name }}</p>
                <p><strong>Price:</strong> ${{ book.price }}</p>
                <p>{{book.image}}</p>
            </div>
            {% endfor %}
        </div>
    </div>
</body>
</html>

market/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Book Details</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f5f5f5;
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }
        h1 {
            color: #333;
            text-align: center;
            margin-bottom: 20px;
        }
        ul {
            list-style: none;
            padding: 0;
            margin: 0;
        }
        li {
            margin-bottom: 10px;
        }
        a {
            text-decoration: none;
            color: #007bff;
        }
        a:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>
<div class="container">
    <h1>Book Store</h1>
    <div>
        <ul>
            {% for book in books %}
            <li>
                <a href="{% url 'market:get_book' book.pk %}">{{ book.name }}</a>
            </li>
            {% endfor %}
        </ul>
        <ul>
            {% if books.has_next %}
                <li><a href="{% url 'market:get_books' %}?page={{ books.next_page_number }}">Next</a></li>
            {% endif %}
        </ul>
        <ul>
            {% if books.has_previous %}
                <li><a href="{% url 'market:get_books' %}?page={{ books.previous_page_number }}">Previous</a></li>
            {% endif %}
        </ul>
    </div>
</div>
</body>
</html>